version: '3'
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - local
  configserver:
    build: .
    ports:
      - "8888:8888"
    networks:
      - local
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
networks:
  local:
    driver: bridge