server:
  port: 8888

spring:
  cloud:
    config:
      server.git.uri: https://github.com/ushisoft/config-repo
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

management:
  endpoints:
    web:
      exposure:
        include: "*"
